# Leader
set -g prefix C-s

# Reload&Apply config
unbind r
bind r source-file ~/.tmux.conf

# Move around
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Allow tmux clipboard to copy to system clipboard
set -s set-clipboard on
# We can set vi bindings in copy mode (accessed with prefix + [) for more crossover with Vim/Neovim:
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'
bind-key -T copy-mode-vi 'C-v' send -X begin-selection \; send -X rectangle-toggle

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
# Auto renumber windows on close
set -g renumber-windows on
# Set passthrough (i.e. Kitty Image Protocol)
set -g allow-passthrough all
set -ga update-environment "TERM_PROGRAM TERM_PROGRAM_VERSION"
set -as terminal-features 'xterm-256color:sixel'

# Windows bindings
bind n new-window
bind-key c command-prompt -I "#W" "rename-window '%%'"
bind -n M-\, previous-window
bind -n M-\. next-window
# Fullscreen chooser, then swap current window with the selected one
bind S choose-tree -Zw "swap-window -t '%%'"

# Pane bindings
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Increase history limit
set -g history-file ~/.tmux-history
set -g history-limit 10000

# Install plugins
set -g @plugin 'tmux-plugins/tpm'  # Plugin Manager
set -g @plugin 'catppuccin/tmux#v2.1.3'

########################
# Configure Catppuccin #
########################

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

# status left look and feel
set -g status-left-length 100
set -g status-left ""
# set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=default,bold]  #S },#{#[bg=default,fg=#{@thm_green}]  #S }}"
set -ga status-left "#{?#{||:#{client_prefix},#{pane_in_mode}},#[fg=#{@thm_mauve}]#[bold],#[fg=#{@thm_green}]}  #S "
set -ga status-left "#[bg=default,fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=default,fg=#{@thm_maroon}]  #{pane_current_command} "
set -ga status-left "#[bg=default,fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=default,fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-left "#[bg=default,fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bf=default,fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

# status right look and feel
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=default,fg=#{@thm_blue}] 󰭦 %Y-%m-%d 󰅐 %H:%M "

# Configure Tmux
set -g status-position top
set -g status-style "bg=default"
set -g status-justify "absolute-centre"

# pane border look and feel
setw -g pane-border-status top
setw -g pane-border-format ""
# setw -g pane-active-border-style "bg=default,fg=#{@thm_overlay_0}"
setw -g pane-border-style "bg=default,fg=#{@thm_surface_0}"
setw -g pane-border-lines single

# # window look and feel
set -wg automatic-rename on
# set -g automatic-rename-format "Window"

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=default,fg=#{@thm_lavender}"
# set -g window-status-last-style "bg=default,fg=#{@thm_peach}"
set -g window-status-activity-style "bg=#{@thm_red},fg=default"
set -g window-status-bell-style "bg=#{@thm_red},fg=default,bold"
set -gF window-status-separator "#[bg=default,fg=#{@thm_overlay_0}]│"
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_bg},fg=#{@thm_green},bold"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
